[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
FerriteMeshParser = "0f8c756f-80dd-4a75-85c6-b0a5ab9d4620"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[sources]
FerriteMeshParser = {path = ".."}
